### ISSUE TITLE
在Android7.1.2上无法正常发送通知

### ISSUE THREAD

**Issue by purofle** [mzdluo123/MiraiAndroid#21]
![Screenshot_20200530-124425](https://user-images.githubusercontent.com/37149302/83319709-65bc4f00-a273-11ea-9cf9-8fa5bbc21d1d.png)
系统：魔趣712
cpu：骁龙616（aarch64）
# 需要抓log吗？

**Comment by mzdluo123** [comment]
这还用问？当然需要

**Comment by purofle** [comment]
> 这还用问？当然需要

## 以下为log
05-30 12:52:50.526
16883:16883/system_process ACRA /ACRA 
	at android.os.Handler.dispatchMessage(Handler.java:102)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.NotificationChannel" on path: DexPathList[[zip file "/data/app/io.github.mzdluo123.mirai.android-1/base.apk"],nativeLibraryDirectories=[/data/app/io.github.mzdluo123.mirai.android-1/lib/arm64, /system/lib64, /vendor/lib64]]

05-30 12:52:50.526
16883:16883/system_process ACRA /ACRA 
	at io.github.mzdluo123.mirai.android.BotApplication.onCreate(BotApplication.kt:47)
05-30 12:52:50.526
16883:16883/system_process ACRA /ACRA 
ACRA caught a NoClassDefFoundError for io.github.mzdluo123.mirai.android
