### ISSUE TITLE
运行时出现异常

### ISSUE THREAD

**Issue by purofle** [mzdluo123/MiraiAndroid#22]
换了台手机....
这次是打开之后直接闪退
系统：emui10.1（android10）
### 下面是log
```
05-30 18:39:11.242  7406  7406 E AndroidRuntime: Process: io.github.mzdluo123.mirai.android, PID: 7406
05-30 18:39:11.242  7406  7406 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.mzdluo123.mirai.android/io.github.mzdluo123.mirai.android.activity.MainActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
05-30 18:39:11.242  7406  7406 E AndroidRuntime: 	at io.github.mzdluo123.mirai.android.activity.MainActivity.onCreate(MainActivity.kt:49)
05-30 18:39:11.242  7406  7406 E ACRA    : ACRA caught a RuntimeException for io.github.mzdluo123.mirai.android
05-30 18:39:11.242  7406  7406 E ACRA    : java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.mzdluo123.mirai.android/io.github.mzdluo123.mirai.android.activity.MainActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
05-30 18:39:11.242  7406  7406 E ACRA    : 	at io.github.mzdluo123.mirai.android.activity.MainActivity.onCreate(MainActivity.kt:49)
```

**Comment by mzdluo123** [comment]
清除数据即可
